// apps/web/src/components/ConnectionBadge.tsx
import type { ConnectionState } from "../types";

export function ConnectionBadge({ connection }: { connection: ConnectionState }) {
  if (connection.status === "checking") {
    return <span className="rounded-full bg-postbox-muted px-4 py-2 text-sm text-postbox-subtle">Checking server…</span>;
  }

  if (connection.status === "connected") {
    return (
      <span className="rounded-full bg-success/10 px-4 py-2 text-sm text-success-foreground ring-1 ring-success/30">
        Connected · protocol {connection.health.protocolVersion}
      </span>
    );
  }

  return (
    <span className="rounded-full bg-warning/10 px-4 py-2 text-sm text-warning-foreground ring-1 ring-warning/30">
      Server unavailable
    </span>
  );
}

// apps/web/src/components/ConnectionBadge.svelte
<script lang="ts">
  import { store } from "../lib/store.svelte";

  const connection = $derived(store.connection);
</script>

{#if connection.status === "checking"}
  <span class="inline-block rounded-full bg-white/10 px-3 py-1 text-xs text-postbox-subtle">Checking server…</span>
{:else if connection.status === "connected"}
  <span class="inline-flex items-center gap-1.5 rounded-full bg-success/10 px-3 py-1 text-xs text-success-foreground ring-1 ring-success/30">
    <span class="h-1.5 w-1.5 rounded-full bg-emerald-400"></span>
    Connected · protocol {connection.health.protocolVersion}
  </span>
{:else}
  <span class="inline-block rounded-full bg-warning/10 px-3 py-1 text-xs text-warning-foreground ring-1 ring-warning/30">
    Server unavailable
  </span>
{/if}
